import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "./components/Header";
import Header from "./components/fe";
import Feed from "./components/Feed";


export default function Home() {
  return (
    <div className="bg-gray-50 min-h-screen">
      <Head>
        <title>Instagram App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Head*/}
      <Header />

      {/*Feed*/}

      <Feed />
      {/*Modal*/}
    </div>
  );
}
